#!/usr/bin/env python
"""
Assemble overview heatmaps of significant TFs across four settings:
  Natural aging (multi-cohort) | SLE (perez_sle) | Ruxolitinib (op) | IL-10 (parsebioscience)

Each panel is the standard overview heatmap (TFs x major cell types, colour = trend),
generated by the same plot_overview_heatmap code path but without its own legends;
one shared cell-type legend and a per-panel trend legend are drawn here.

Output: PLOTS_DIR/assembled/overview_all_conditions.png
"""

import os
import sys
import warnings
import numpy as np
import matplotlib.pyplot as plt
from argparse import Namespace
from matplotlib.patches import Patch
from PIL import Image, ImageChops

warnings.filterwarnings("ignore")

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))

from hira import retrieve_stats, retrieve_sig_stats
from hira.src.config import PLOTS_DIR, MAJOR_CTS, get_config_fa, palette_major_cts, surrogate_names
from hira.src.feature_association.plots_condition import plot_overview_heatmap
from hira.src.feature_association.helper_condition import get_condition_palette

plt.rcParams.update({"figure.dpi": 150, "font.family": "Arial", "font.size": 10})

ASSEMBLED_DIR = os.path.join(PLOTS_DIR, "assembled")
PANEL_DIR = os.path.join(ASSEMBLED_DIR, "_panels")  # keep the pipeline's overview_*.png intact
ANALYSIS_NAME = "tfa_major_b"

# (dataset key, analysis_type, panel title)
PANELS = [
    ("aging",           "aging",        "Natural aging"),
    ("perez_sle",       "disease",      "SLE"),
    ("op",              "perturbation", "Ruxolitinib"),
    ("parsebioscience", "perturbation", "IL-10"),
]


def make_args(dataset, analysis_type):
    cfg = get_config_fa(ANALYSIS_NAME)
    return Namespace(dataset=dataset, analysis_type=analysis_type, analysis_name=ANALYSIS_NAME,
                     output_dir=PANEL_DIR, cell_types=MAJOR_CTS, granularity=cfg['granularity'],
                     feature_type=cfg['feature_type'], data_type=cfg['data_type'])


def get_stats(dataset):
    """Significant stats fed to the overview heatmap, one row per gene x cell type."""
    if dataset == 'aging':
        return retrieve_sig_stats(analysis_name=ANALYSIS_NAME).drop_duplicates(subset=['cell_type', 'gene'])
    stats = retrieve_stats(dataset=dataset, analysis_name=ANALYSIS_NAME, multi_cohort=False)
    stats = stats[stats['is_significant']]
    if dataset == 'perez_sle':
        stats = stats[stats['age_group'] == 'Both age groups']
    return stats


def trim(img):
    """Drop the white border so panels sit tight against their titles and neighbours."""
    rgb = img.convert("RGB")
    bbox = ImageChops.difference(rgb, Image.new("RGB", rgb.size, (255, 255, 255))).getbbox()
    return img.crop(bbox) if bbox else img


def assemble():
    os.makedirs(PANEL_DIR, exist_ok=True)
    panels = []
    for dataset, analysis_type, title in PANELS:
        print(f"  Generating overview: {title} ({dataset}) ...")
        stats = get_stats(dataset)
        plot_overview_heatmap(stats, make_args(dataset, analysis_type), show_legend=False)
        palette = get_condition_palette(analysis_type)
        trends = {t: palette[t] for t in stats['trend'].unique()}
        panels.append((os.path.join(PANEL_DIR, f"overview_{dataset}.png"), title, trends))

    imgs = [trim(Image.open(path)) for path, _, _ in panels]
    # axes as wide as their image so imshow leaves no side margins
    fig, axes = plt.subplots(1, len(panels), figsize=(6, 3),
                             gridspec_kw={"wspace": 0.06,
                                          "width_ratios": [im.width / im.height for im in imgs]})
    seen = {}  # trend label -> colour; ruxolitinib and IL-10 share the treatment labels
    for ax, im, (path, title, trends) in zip(axes, imgs, panels):
        ax.imshow(np.array(im), aspect='auto')  # fill the axes so panels sit side by side
        ax.axis("off")
        ax.set_title(title, fontsize=11, fontweight="bold", pad=10)
        seen.update(trends.items())

    fig.legend(handles=[Patch(color=c, label=l, alpha=.8) for l, c in seen.items()],
               loc="upper center", bbox_to_anchor=(0.5, 0.04), ncol=3, frameon=False, fontsize=8,
               handlelength=0.8, handleheight=0.8, handletextpad=0.4, columnspacing=1.2)

    fig.legend(handles=[Patch(color=palette_major_cts[ct], label=surrogate_names.get(ct, ct)) for ct in MAJOR_CTS],
               title="Cell type", loc="center left", bbox_to_anchor=(1.01, 0.5),
               bbox_transform=axes[-1].transAxes, frameon=False, fontsize=8, title_fontsize=9,
               handlelength=0.8, handleheight=0.8, handletextpad=0.4, labelspacing=0.25)

    os.makedirs(ASSEMBLED_DIR, exist_ok=True)
    out = os.path.join(ASSEMBLED_DIR, "overview_all_conditions.png")
    fig.savefig(out, bbox_inches="tight", dpi=300, transparent=True)
    plt.close(fig)
    print(f"\nSaved assembled figure: {out}")


if __name__ == "__main__":
    assemble()
